### ISSUE TITLE
BUG - Nav Mesh Driven Movement - Animator Parameters don't update to match movement settings

### ISSUE THREAD

**Issue by Drenyn** [Black-Horizon-Studios/Emerald-AI-2024#1]
The Animator Parameter for Speed is set for Idle (Stationary) to be at 0, Walk to be at 0.5, and Run to be at 1.

However the Speed parameter is being set in the Movement Settings, and is using the Walk Speed and Run Speed as the "Speed" parameter.   This causes the AI to run, when they should be walking, as the default walk speed is 2, when first creating an AI.  Workaround is to update the parameters manually to match the speeds that will be used, however if previous Emerald Versions, this updated automatically.

Thanks!

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report, I'll get it fixed asap.

**Comment by Black-Horizon-Studios** [comment]
I released an update that fixes the issues with the Animator speed not calculating correctly. This rework allows Nav Mesh driven movement to work without having to set the Animator Speed variable to different values.
