### ISSUE TITLE
Opening Animation Viewer in 'Open Prefab in Context' causes errors and unity editor crash

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#10]
If I try to open an AI prefab in context, then open the Animation Viewer, it causes a 'Stage Error' with this text 'Error: The root GameObject of the opened Prefab has been moved out of the Prefab Stage scene by a script.'

You can close the error window but just after that consistently get an editor crash.

Opening the animation viewer on a prefab in the scene (not in open in context, or open in isolation) works fine.

Unity 2021.3.33f1

**Comment by Black-Horizon-Studios** [comment]
Yes, it is a Scene View tool, not a prefab tool. However, I can stop the button from working if it’s not within the scene. Thanks for the bug report.

**Comment by Black-Horizon-Studios** [comment]
I have found a solution for this and it will be included with the 1.0.5 update. Users will no longer be able to press the Open Animation Viewer button from within the Project tab. There's also a message that has been added to notify the user of this.
