### ISSUE TITLE
Deactivate check on Dead AIs causes an error

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#11]
I get this on AIs that are dead and have optimization on - 

"SetDestination" can only be called on an active agent that has been placed on a NavMesh.
UnityEngine.AI.NavMeshAgent:set_destination (UnityEngine.Vector3)
EmeraldAI.Utility.VisibilityCheck:Deactivate () (at Assets/3rdParty/Emerald AI/Scripts/Internal/VisibilityCheck.cs:113)

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report, I'll get it fixed.

**Comment by Black-Horizon-Studios** [comment]
Alright, I've found a solution. This will be fixed with the upcoming version 1.0.5.1.
