### ISSUE TITLE
Documentation bug in "Using an Attract Modifier" page?

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#12]
https://black-horizon-studios.gitbook.io/emerald-ai-wiki/emerald-components-optional/sound-detector-component/using-an-attract-modifier

I think you meant to say 'object' instead of 'AI' here:

Step 1
Find the AttractModifier script by searching for AttractModifier within the Project tab. Drag and drop it at the top of your **AI**.

**Comment by Black-Horizon-Studios** [comment]
Thanks for the report, I've update it. For some reason the pictures for those sections were not displaying correctly and I've also fixed that.
