### ISSUE TITLE
Multi-weapon issues, AI won't switch attack types and gets hung up (no weapon objects/holstering)

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#14]
(copying this one from discord)

I think this one is somehow related to the fact that this AI type doesn't have any weapon objects or holstering/draw anims, as I have another 2-weapon AI that does have weapons and it doesn't do this behavior (although I still have the issue that the weapon 2 list isn't showing up in the Items component for it).

I'm seeing some weirdness with another AI that has a melee and ranged weapon type. No weapon objects/holstering involved in this one, the melee is a claw animation attack and ranged is a projectile ability. I can get each weapon type working individually but when they are together in a 2 weapon type config the AI will start ok, doing ranged attacks when player is at a distance, but if I get close it won't switch to melee and seems to get hung up and won't respond at all after that. Weapon type switch is "Distance" set to 3. The distance ranges for the attacks in each case look right and work in the individual cases properly. I lowered the switch cooldown to 1 to make sure that wasn't the cause and it still occurs.

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report.

This issue has already been reported and has been fixed with the upcoming 1.0.6 update. This update should be live some time tomorrow.

**Comment by raygresko** [comment]
awesome thanks - yeah I just got it working by putting some equip/unequip anims on both the weapon types and it started working. My case didn't really need equip/unequip anims, since it's just changing from melee hand attacks to a spell cast.

Thanks for the fast turnaround on the fixes! :)
