### ISSUE TITLE
Null reference in GenerateRandomPositionWithinRadius()

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#17]
Started getting this with the 1.06 version (I think EmeraldComponent.CombatTarget is null):

NullReferenceException: Object reference not set to an instance of an object
EmeraldAI.EmeraldAPI+Internal.GenerateRandomPositionWithinRadius (EmeraldAI.EmeraldSystem EmeraldComponent) (at Assets/3rdParty/TECHANDTOOLS/Emerald AI/Scripts/Internal/EmeraldAPI.cs:929)
EmeraldAI.EmeraldDetection.ObstructionAction () (at Assets/3rdParty/TECHANDTOOLS/Emerald AI/Scripts/Components/Required/EmeraldDetection.cs:247)
EmeraldAI.EmeraldDetection.DetectionUpdate () (at Assets/3rdParty/TECHANDTOOLS/Emerald AI/Scripts/Components/Required/EmeraldDetection.cs:188)
EmeraldAI.EmeraldSystem.Update () (at Assets/3rdParty/TECHANDTOOLS/Emerald AI/Scripts/Components/Required/EmeraldSystem.cs:145)

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report.

Can you please tell me what you did to get this bug?

**Comment by raygresko** [comment]
It just started happening after the upgrade, no changes from what I was doing before. For now, I just added a check if the CombatTarget is is null and return.

**Comment by Black-Horizon-Studios** [comment]
Updated: Never mind, I was able to recreate it. It looks like happens when the CombatTarget is cleared while the GenerateRandomPositionWithinRadius function is running.

**Comment by Black-Horizon-Studios** [comment]
All fixed, I will be releasing a quick update (v1.0.6.1) to address this. Thanks again for the bug report.
