### ISSUE TITLE
OnReachedDestination Event not execute

### ISSUE THREAD

**Issue by MM501025** [Black-Horizon-Studios/Emerald-AI-2024#18]
OnReachedDestination event is not called. Attempting to access the event manuell is also unsuccessful. "_aiSystem.EventsComponent.OnReachedDestinationEvent.AddListener(() => this.OnReachedDestination());". No error message is displayed either.

**Comment by Black-Horizon-Studios** [comment]
I have tested the OnReachedDestinationEvent and it is being invoked correctly. Keep in mind OnReachedDestinationEvent will only invoke for the Destination Wander Type. You can use OnReachedWaypointEvent for all other destination related events.
