### ISSUE TITLE
NavMesh "SetDestination" error EmeraldBehavior

### ISSUE THREAD

**Issue by dopper3** [Black-Horizon-Studios/Emerald-AI-2024#19]
When I kill an AI, I get the following error:

"Set Destination" can only be called on an active agent that has been place on a NavMesh.

The error occurs here:

`        /// <summary>
        /// When detecting a target, update the AI's current destination to be equal to their current position until the combat movement code can take over.
        /// </summary>
        public virtual void OnDetectTarget()
        {
            BehaviorState = "Cautious";
            EmeraldComponent.m_NavMeshAgent.SetDestination(transform.position);
        }`

If I add a check for isActiveandEnabled, it fixes the issue:

`        /// <summary>
        /// When detecting a target, update the AI's current destination to be equal to their current position until the combat movement code can take over.
        /// </summary>
        public virtual void OnDetectTarget()
        {
            BehaviorState = "Cautious";
            if (isActiveAndEnabled) EmeraldComponent.m_NavMeshAgent.SetDestination(transform.position);
        }`

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report and solution. I’ve added the fix to the upcoming 1.1.2 update.
