### ISSUE TITLE
Bug - On Start Combat Event and On End Combat Event being Invoked at incorrect time.

### ISSUE THREAD

**Issue by Drenyn** [Black-Horizon-Studios/Emerald-AI-2024#2]
Currently the On Start Combat Event and On End Combat Event is being Invoked when a player or detected target comes into the Detection Distance, but ignores the Field of View.   Any ways to have this only trigger once the AI goes into the Combat state, such as Combat Movement or Combat Attack, rather than just being invoked even though nothing as technically be detected yet?

Thanks!

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report. 

I'll add the condition for these events to only work within the Field of View and only when a target is actually detected.

**Comment by Black-Horizon-Studios** [comment]
I looked into this and I cannot recreate it. For me, the OnStartCombat event only triggers after a target or player is detected and it works with field of view. 

Any tips to recreate your issue?

**Comment by Drenyn** [comment]
The easiest way I've been able to recreate this, was by just using the Events and putting the Emerald UI to bool enable on "OnStartCombat" and disable "OnEndCombat".   Then I just move closer to the enemy and watch it enable and disable, while completely behind the enemy (so not in field of view) but within detection range if they were to turn around.

**Comment by Black-Horizon-Studios** [comment]
Yes, this is how the health bar is enabled, when you enter an AI's detection radius, whether or not a target is detected.

I tested this with a Debug Log event (through the Debugger Component) and both events were invoked when they were supposed to.

**Comment by Drenyn** [comment]
Sorry for the misunderstanding.  Thank you for your help on this.  :)

**Comment by Black-Horizon-Studios** [comment]
No worries and you're welcome!
