### ISSUE TITLE
Location Based Damage Integration

### ISSUE THREAD

**Issue by dopper3** [Black-Horizon-Studios/Emerald-AI-2024#20]
Hi, not really a bug but an update for the InvectorAIBridge script to allow it to work with LocationBasedDamageArea. This is my udpated InvectorAIBridge script:

`
    public class dd_InvectorAIBridge : vHealthController    {
        IDamageable m_IDamageable;
        EmeraldHealth m_EmeraldHealth;

        bool hasLBD = false;

        protected override void Start()
        {
            base.Start();

            m_IDamageable = GetComponent<IDamageable>();
            m_EmeraldHealth = GetComponent<EmeraldHealth>();

            if (GetComponent<LocationBasedDamage>()) hasLBD = true; // check if AI is using LBD. If it is, use LBD area

            maxHealth = m_EmeraldHealth.StartingHealth;
            _currentHealth = m_EmeraldHealth.CurrentHealth;
        }

        public override void TakeDamage(vDamage damage)
        {
            base.TakeDamage(damage);

            if (!hasLBD)
            {
                m_IDamageable.Damage((int)damage.damageValue, damage.sender, 100);
            }
            else
            {
                LocationBasedDamageArea m_LBD_Area = damage.receiver.GetComponent<LocationBasedDamageArea>();
                m_LBD_Area.DamageArea((int)damage.damageValue, damage.sender, 100);
            }
        }
    }
}`

**Comment by Black-Horizon-Studios** [comment]
Thanks for this improvement. I'll get it added to the InvectorAIBridge script when I get the chance.
