### ISSUE TITLE
AI behavior has bugs

### ISSUE THREAD

**Issue by LeekinGTA** [Black-Horizon-Studios/Emerald-AI-2024#21]
unity version：2020.3.16f1c1 LTS
emerald AI2024Version：1.0.7.1
Use the api to set the NPC object to follow the player EmeraldAPI.Detection.SetTargetToFollow(EmeraldComponent,player.transform);
And use the API to make NPCs become warriors:
EmeraldAPI.Behaviors.ChangeBehavior(EmeraldComponent, EmeraldBehaviors.BehaviorTypes.Aggressive);
Start debugging. After the NPC comes to the player's position, the player continues to move and the NPC no longer follows the player. What should be done?

**Comment by Black-Horizon-Studios** [comment]
I have tested this and everything seems to be working correctly and you were able to resolve your issue. So, I am closing this bug report.
