### ISSUE TITLE
Unity crash with condition module & grenade ability

### ISSUE THREAD

**Issue by bma42** [Black-Horizon-Studios/Emerald-AI-2024#23]
I noticed that when the condition module was activated on the grenade ability, Unity would crash when entering play mode and the grenade was thrown.
Unity freezes, forcing the application to be force quit. Moreover, it seems that the other abilities are affected as well.

Unity 2022.3.37f1 silicon (Metal)
Mac OS

**Comment by Black-Horizon-Studios** [comment]
Thanks, this is fixed with the 1.2.5 update.

**Comment by Black-Horizon-Studios** [comment]
Thanks, this is fixed with the 1.2.5 update.
