### ISSUE TITLE
Player not being recognized by AI after death

### ISSUE THREAD

**Issue by REZAALIDAD** [Black-Horizon-Studios/Emerald-AI-2024#24]
Player not being recognized by AI after death 
After the player dies, AI can't find the player and the following error is given
Only ai that is not idle gives this error
----------------------------------------------------------------------------------------------------------
 MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.get_position () (at <53aac14d88ba4477acc998b039cfd73a>:0)
EmeraldAI.SoundDetection.EmeraldSoundDetector.UpdateTargetData () (at Assets/Emerald AI/Scripts/Components/Optional/Sound Detection/EmeraldSoundDetector.cs:173)
EmeraldAI.SoundDetection.EmeraldSoundDetector.CheckForSounds () (at Assets/Emerald AI/Scripts/Components/Optional/Sound Detection/EmeraldSoundDetector.cs:144)
EmeraldAI.SoundDetection.EmeraldSoundDetector.Update () (at Assets/Emerald AI/Scripts/Components/Optional/Sound Detection/EmeraldSoundDetector.cs:158)

**Comment by Black-Horizon-Studios** [comment]
Thanks, this is fixed with the 1.2.5 update.
