### ISSUE TITLE
The character ignores the weapon change

### ISSUE THREAD

**Issue by tomkass2** [Black-Horizon-Studios/Emerald-AI-2024#3]
The character ignores the weapon change from type 1 to type 2 if I set the distance change option.. Only one weapon works, which is marked as default

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report, I'll get right on fixing it.

I fixed the other issues you had with the NavMesh Movement Type. The update is already live on the Asset Store. I'd appreciate it if you updated your review :)

**Comment by Black-Horizon-Studios** [comment]
The update that fixes this bug is now live on the Asset Store. 

Thanks for reporting the bug!
