### ISSUE TITLE
Animation View Event missing

### ISSUE THREAD

**Issue by Drenyn** [Black-Horizon-Studios/Emerald-AI-2024#4]
In the Emerald AI 2024 Wiki there is a video that shows there should be an "Emerald Attack Event" in the event type drop down list for the Animation Viewer, however that event is not there in the current version.   Thanks!
![Screenshot 2023-12-18 011128](https://github.com/Black-Horizon-Studios/Emerald-AI-2024/assets/46606148/16c8a431-fb42-45f6-b52d-dcd02560fd7b)

**Comment by Black-Horizon-Studios** [comment]
Yes, this was renamed since that clip was taken to be Create Ability. 

Create Ability is the equivalent of Emerald Attack Event.
