### ISSUE TITLE
Window for Animation Viewer Stuck at one size clipping off the later menu options. 

### ISSUE THREAD

**Issue by WhiteDaniel** [Black-Horizon-Studios/Emerald-AI-2024#5]
Not sure if this is unty or the asset or both but I can't access the rest of the window for the Animation Viewer. 2021.3.5f1 version of Unity 

![2023-12-18 22-28-010](https://github.com/Black-Horizon-Studios/Emerald-AI-2024/assets/92885994/45c5bb13-7d30-4698-ac6b-c99fa53bc2fb)

**Comment by Black-Horizon-Studios** [comment]
What version are you using? This issue was addressed with the 1.0.3 update I released yesterday. 

Also, what's the resolution of your monitor? The size partially based off of the resolution.

**Comment by Black-Horizon-Studios** [comment]
I haven't heard back and I fixed this issue with a previous update so I'm marking this as closed.
