### ISSUE TITLE
AIs are always using run animations, even when 'walking'

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#6]
My AIs when in wander mode with no enemies detected always use their run animation instead of the walk anim, even though the 'Movement Animation' toggle in the Movement component->Movement Settings is set to 'Walk'.

The walk animations look to be set up correctly in the animation editor, and play in the previewer correctly.

**Comment by Black-Horizon-Studios** [comment]
Hey there, thanks for the bug report.

What version are you using? This issue was fixed with the 1.0.2 update.

**Comment by raygresko** [comment]
oops my bad - just updated and this is working now, sorry I missed the update.

**Comment by Black-Horizon-Studios** [comment]
No worries :)
