### ISSUE TITLE
EmeraldAPI.Movement.StopMovement doesn't stop dynamic wandering AIs from animating

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#7]
I have a wandering AI that I use StopMovement on for conversations. The AI will stop moving but continue doing walk/run animations. If I catch it while it is idle at a dynamic waypoint, it will start walking in place once it gets to be time for it to wander to a new waypoint.

**Comment by Black-Horizon-Studios** [comment]
Thanks, I'll look into this.

**Comment by Black-Horizon-Studios** [comment]
I was able to identify the bug and find a solution. AI will now properly stop and play their idle animation when using the StopMovement API. They will then continue moving properly after using the ResumeMovement API.

I will be submitting this update soon. Thanks again for the bug report.
