### ISSUE TITLE
When Ai is in non combat mode and get hit by bullet he never draws/equips his weapon 

### ISSUE THREAD

**Issue by hrohibil** [Black-Horizon-Studios/Emerald-AI-2024#8]
Hey. 
Using the equip / unequip - it works perfect when player walks close to be detected then he draws out his weapon as expected. But if I shoot at him BEFORE he has played the draw weapon animation and hit him then he immediately goes into attack and shoots at player but without drawing the weapon… So he has no visible weapon but are playing the attack animation

**Comment by Black-Horizon-Studios** [comment]
Thanks for the bug report.

I've fixed this with the 1.0.5 update, which should be live soon. It will require you to regenerate the Animator Controller through an AI's Animation Profile (for any AI that you have created outside of the included demo AI).
